### ISSUE TITLE
OutOfMemoryError kills Worker

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#116]
### Description
I am currently running another stress test and noticed, that if a OutOfMemoryError Exception is thrown **the entire worker dies.**
```
worker_1   | Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
worker_1   |   at org.eclipse.jgit.internal.storage.file.PackFile.load(PackFile.java:815)
worker_1   |   at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:285)
worker_1   |   at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:486)
worker_1   |   at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:444)
worker_1   |   at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:435)
worker_1   |   at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:165)
worker_1   |   at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:224)
worker_1   |   at org.eclipse.jgit.diff.DiffFormatter.makeIteratorFromTreeOrNull(DiffFormatter.java:490)
worker_1   |   at org.eclipse.jgit.diff.DiffFormatter.scan(DiffFormatter.java:481)
worker_1   |   at org.eclipse.jgit.diff.DiffFormatter.scan(DiffFormatter.java:455)
worker_1   |   at refactoringml.ProcessMetricsCollector.collectProcessMetricsOfStableCommits(ProcessMetricsCollector.java:81)
worker_1   |   at refactoringml.ProcessMetricsCollector.collectMetrics(ProcessMetricsCollector.java:52)
worker_1   |   at refactoringml.App.run(App.java:175)
worker_1   |   at refactoringml.RunQueue.doWork(RunQueue.java:86)
worker_1   |   at refactoringml.RunQueue.run(RunQueue.java:72)
worker_1   |   at refactoringml.RunQueue.main(RunQueue.java:55)
db_1       | 2020-03-11 11:51:44 12 [Warning] Aborted connection 12 to db: 'refactoringdb' user: 'root' host: '172.18.0.6' (Got an error reading communication packets)
db_1       | 2020-03-11 11:51:44 9 [Warning] Aborted connection 9 to db: 'refactoringdb' user: 'root' host: '172.18.0.6' (Got an error reading communication packets)
db_1       | 2020-03-11 11:51:44 8 [Warning] Aborted connection 8 to db: 'refactoringdb' user: 'root' host: '172.18.0.6' (Got an error reading communication packets)
worker_1   | Done!!
data-collection_worker_1 exited with code 0
```

### Handling
 I am not sure how to handle this exception:
1. Shutdown the entire App class, remove the project from the database and move on to the next one.
2. Try to recover in the App class, recover the SessionConfig and only skip the commit.

**Comment by mauricioaniche** [comment]
I'd say the simplest solution would be to create a simple python wrapper that restarts the app if it crashes. Or maybe there's already a linux cmd for that?

**Comment by jan-gerling** [comment]
> I'd say the simplest solution would be to create a simple python wrapper that restarts the app if it crashes. Or maybe there's already a linux cmd for that?

We could restart the RunQueue with Linux cmd in the run could.sh:
```
RC=1
while [ $RC -ne 0 ]; do
   ./java -Xmx800m -Xms350m -cp $REFACTORINGMINER_JAR_PATH:$JAR_PATH $QUEUE_CLASS
   RC=$?
done
```

**Comment by mauricioaniche** [comment]
Good solution!
