### ISSUE TITLE
No Commit Found in Walk Bug

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#119]
**Linked to: #95** 

During the second stress testing this error was thrown quite often:
`java.lang.NullPointerException` after trying to fetch a RevCommit from the walk.
https://github.com/refactoring-ai/predicting-refactoring-ml/blob/7e49886dc775bd3bf5218c555e50c7e9b162a2dd/data-collection/src/main/java/refactoringml/ProcessMetricsCollector.java#L137

## Example
2020-03-12 10:27:19 ERROR ProcessMetricsCollector:165 java.lang.NullPointerException when processing metrics for commit: 73f520a0c329070cf03a4272a16c09f5263ff04e
java.lang.NullPointerException: null
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:138) ~[refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:888) ~[refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:800) ~[refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.util.JGitUtils.getReverseWalk(JGitUtils.java:74) ~[refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.ProcessMetricsCollector.outputNonRefactoredClass(ProcessMetricsCollector.java:137) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.ProcessMetricsCollector.collectProcessMetricsOfStableCommits(ProcessMetricsCollector.java:118) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.ProcessMetricsCollector.collectMetrics(ProcessMetricsCollector.java:52) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.run(App.java:174) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processRepository(RunQueue.java:86) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.run(RunQueue.java:59) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.main(RunQueue.java:42) [refactoring-analyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]

## Solution
Remove the RevCommit and change it back to a commitId String, because it is sufficient.

**Comment by jan-gerling** [comment]
Fixed on 21319e0.
