### ISSUE TITLE
CK Timeouts on TrezorMessage

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#132]
CK failed **17** times to extract the metrics **within 20 seconds** for the following file (app/src/main/java/com/satoshilabs/trezor/protobuf/TrezorMessage.java **?**):
 `2020-03-13 20:38:31 ERROR CKUtils:36 CK failed to calculate metrics for /tmp/1584131891004-0/ on the commit 9051a6153e8905e6bb7e61ca07719b83753330b1 in the project: https://www.github.com/greenaddress/GreenBits.git with a timeout of 20 seconds.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[?:?]
	at refactoringml.util.CKUtils.calculate(CKUtils.java:34) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RefactoringAnalyzer.calculateCkMetrics(RefactoringAnalyzer.java:172) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RefactoringAnalyzer.collectCommitData(RefactoringAnalyzer.java:106) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.processCommit(App.java:203) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.run(App.java:134) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processRepository(RunQueue.java:99) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processResponse(RunQueue.java:66) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.run(RunQueue.java:57) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.main(RunQueue.java:44) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]`

**Comment by mauricioaniche** [comment]
I'll take a look. There's a similar class in CK's test suite now, and it works just fine: https://github.com/mauricioaniche/ck/tree/master/fixtures/real-world-huge-class

**Comment by mauricioaniche** [comment]
The CK exception didn't happen here. I got 11 RefactoringMiner timeouts, but 0 CK timeouts.

**Comment by jan-gerling** [comment]
> The CK exception didn't happen here. I got 11 RefactoringMiner timeouts, but 0 CK timeouts.
It is probably related to the available resources. Do you know how much memory processing the class consumes?

**Comment by mauricioaniche** [comment]
When doing the db PR, I noticed that some commits really take a good amount of seconds... Maybe we need some more fine-grained log data there, e.g., to know how long it takes in RMiner, how long it takes in CK. That'll be the best way for us to measure CK's performance.

**Comment by mauricioaniche** [comment]
Just opened an issue for it: https://github.com/refactoring-ai/predicting-refactoring-ml/issues/136

**Comment by jan-gerling** [comment]
This issue is solved by increasing the timeout for CK. See the results from stress test 05 #95
