### ISSUE TITLE
Projects failing during initialization

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#148]
Two projects **failed during initialization** with an java.lang.IllegalArgumentException. This is a **fatal bug** and should never happen.
```
/data-collection_worker_3 2020-03-17 19:58:40 ERROR RunQueue:113 Error while processing https://github.com/Rudloff/openvegemap-cordova.git
java.lang.IllegalArgumentException: /tmp/1584475106676-0/repo/www does not exist
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2413) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.initProject(App.java:169) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.run(App.java:109) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processRepository(RunQueue.java:111) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processResponse(RunQueue.java:66) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.run(RunQueue.java:57) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.main(RunQueue.java:44) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
/data-collection_worker_3 2020-03-17 19:58:59 ERROR RefactoringAnalyzer:76 Failed to collect commit data for refactored commit: 8b11eb8d004f0c1856d229641329f9cc687a4bd8
```
```
/data-collection_worker_3 2020-03-17 20:09:38 ERROR RunQueue:113 Error while processing https://github.com/jpcap/jpcap.git
java.lang.IllegalArgumentException: /tmp/1584475776510-0/repo/src/java/net/sourceforge/jpcap/client/libjpcap.jnilib does not exist
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2413) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOf(FileUtils.java:2417) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2479) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.initProject(App.java:169) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.App.run(App.java:109) ~[data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processRepository(RunQueue.java:111) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.processResponse(RunQueue.java:66) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.run(RunQueue.java:57) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at refactoringml.RunQueue.main(RunQueue.java:44) [data-collection-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
/data-collection_worker_3 2020-03-17 20:13:19 ERROR RefactoringAnalyzer:76 Failed to collect commit data for refactored commit: 909f677f912ed1a01b4ef39f2bd7e6b068d1f19e
```

**Comment by jan-gerling** [comment]
This issue might be related to:
https://jonisalonen.com/2012/java-and-file-names-with-invalid-characters/

**Comment by mauricioaniche** [comment]
If they fail during cloning, let's just skip them. We have so many projects to explore, that they won't make a difference.
